package com.paw.notifications.domain;

public enum NotificationType {
    NGO_REGISTRATION_CREATED,
    NGO_REGISTRATION_APPROVED,
    NGO_REGISTRATION_REJECTED,
    USER_STATUS_CHANGED,
    ADOPTION_APPLICATION_CREATED,
    ADOPTION_APPLICATION_ACCEPTED,
    ADOPTION_APPLICATION_REJECTED,
    ADOPTION_APPLICATION_INFO_REQUESTED,
    ANIMAL_CREATED,
    ANIMAL_UPDATED,
    ANIMAL_ADOPTED,
    DONATION_CREATED,
    DONATION_APPROVED,
    DONATION_REJECTED,
    DONATION_PENDING,
    DONATION_REFUNDED,
    CAMPAIGN_CREATED,
    CAMPAIGN_UPDATED,
    CAMPAIGN_GOAL_REACHED,
    CAMPAIGN_FINISHED,
    CAMPAIGN_EXPIRED,
    FEED_POST_PUBLISHED,
    FEED_POST_ARCHIVED,
    SYSTEM_ALERT
}